# Generated by Django 4.2.11 on 2024-04-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='uid')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема сообщения')),
                ('date_time_sent', models.DateTimeField(verbose_name='дата/время отправления письма')),
                ('date_received', models.DateTimeField(auto_now_add=True, verbose_name='дата получения письма')),
                ('body', models.TextField(verbose_name='текст письма')),
            ],
        ),
        migrations.CreateModel(
            name='MailFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='mail_app.mails', verbose_name='файл')),
            ],
        ),
    ]
