# Generated by Django 4.2.11 on 2024-04-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mails',
            new_name='Mail',
        ),
    ]
