# Generated by Django 4.2.11 on 2024-04-25 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_rename_mails_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_from',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Письмо от '),
            preserve_default=False,
        ),
    ]
