# Generated by Django 4.2.11 on 2024-04-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0005_mailfiles_file_url_alter_mailfiles_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailfiles',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='скачать файл'),
        ),
    ]
